# Generated by Django 5.2.1 on 2025-05-15 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField()),
                ('numero_telephone', models.CharField(max_length=15)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_scanne', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
    ]
