# Generated by Django 5.2.1 on 2025-05-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_remove_participant_est_scanne_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='jour_evenement',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
